### ISSUE TITLE
Assign pixel size

### ISSUE THREAD

**Issue by jianhaoc** [rsanchezgarc/deepEMhancer#10]
Hi, I find in output that "DONE!. Shape at 1.00 A/voxel after padding->  (288, 288, 288)"
Is it assign the 1.00A pixelsize? Can I set up a accurate pixel size option? Thank you!

**Comment by rsanchezgarc** [comment]
Hi,

DeepEMhancer uses the sampling rate that is contained in the header of the mrc file. Then, internally, it downsamples/upsample your map to 1 A/voxel and applies paddingt to a multiple of the network internal size. The information you are reading is only for letting you know the internal process, but you shouldn't care about it if your mrc file has a proper header. In case your header is incorrect, you can always provide it using the option --samplingRate CORRECT_SAMPLING

Hope it helps.

Ruben
