### ISSUE TITLE
Configuring defaults model path

### ISSUE THREAD

**Issue by rsanchezgarc** [rsanchezgarc/deepEMhancer#12]
As asked by @alburse I can add an environmental variable to set an alternative one. Just curious about what are the reasons you find the default one (in ~/.local/share/) inconvenient.

Thanks a lot.

Ruben

**Comment by alburse** [comment]
2 reasons. We have 2 versions of deepemhancer right now, one with cuda10 and another with cuda11 and their models are different. More importantly, I installed deepemhancer in a computer cluster where multiple people use it so it is more convenient to keep the models in a path that all the users have acccess.

**Comment by rsanchezgarc** [comment]
Thanks, I see your point.

What would you think if I create a file during the --download that will be saved in the same directory that DeepEMhancer was installed (presumably within your anaconda env directory) that will contain the path where the model was downloaded?

Ruben

**Comment by alburse** [comment]
Like a configuration file. That is perfectly fine I think.

**Comment by rsanchezgarc** [comment]
Hi,

The file deepEMhancer/config.py contains the variable DEFAULT_MODEL_DIR. Editing that file should be sufficient for your purpose.
Please, let me know if you need something else

**Comment by alburse** [comment]
Perfect. Thanks
