### ISSUE TITLE
radial noise >37.0% killed

### ISSUE THREAD

**Issue by sojoberry** [rsanchezgarc/deepEMhancer#14]
I'm guessing that this file has too much noise for DeepEMhancer?

$ deepemhancer -i cryosparc_P5_J223_007_volume_map_sharp.mrc -o J223_deepemhanced.mrc
updating environment to select gpu: [0]
Using TensorFlow backend.
loading model /home/sojoseph/.local/share/deepEMhancerModels/production_checkpoints/deepEMhancer_tightTarget.hd5 ... DONE!
Automatic radial noise detected beyond 37.0 % of volume side
Killed

**Comment by rsanchezgarc** [comment]
Hi,

When you get the "Killed" message, it is generally caused by getting out of RAM memory. How big is your map and how much RAM memory does your machine have?

Ruben

**Comment by sojoberry** [comment]
Thanks for the prompt reply Ruben,

The issue was with the install of DeepEMhancer through SBGrid. It was fixed by using: export DEEPEMHANCER_X=20210511.
It wasn't to do with memory even though that's what the error message said.

Cheers,
Soumya

**Comment by sojoberry** [comment]
Hi Ruben, I tried running deepEMhancer on a 4-A structure of a mucin-like
protein. It tends to erase the mucin domain density. Probably because it
hasn't trained on anything like heavily glycosylated protein before (also
plenty of O-glycosylation).
Thanks for willing to help Ruben,
Soumya

**Comment by rsanchezgarc** [comment]
Hi Soumya,

Thanks for reporting. I am sorry it didn't work

Best wishes,

Ruben
