### ISSUE TITLE
deepemhancer version

### ISSUE THREAD

**Issue by jianhaoc** [rsanchezgarc/deepEMhancer#16]
Hi, how to find the version of deepemhancer? Neither deepemhancer -h nor -v doesn't help.

**Comment by rsanchezgarc** [comment]
Hi,

Thank you very much for letting me know, I will fix the -v problem. The version is included in the setup.py file
https://github.com/rsanchezgarc/deepEMhancer/blob/5bb9ef65dfabb2bdeab2cbaa757589ad6e57708b/setup.py#L6, so you can check it manually while I am fixing it.
