### ISSUE TITLE
getting Error when running deepemhancer test run

### ISSUE THREAD

**Issue by JYlag** [rsanchezgarc/deepEMhancer#17]
Hello there,

ENV:
Python 3.7.5
Ubuntu 18.04
CUDA 10.0
Nvidia Drivers 410.48
Kernel 4.15.0
GCE VM

I am running the following command:
`deepemhancer -i <input-mrc> -o <output.mrc>`

I am getting the following error:

> john_doe@vm:~$ deepemhancer -i run_class001.mrc -o test.mrc
> updating environment to select gpu: [0]
> Using TensorFlow backend.
> loading model /home/john_doe/.local/share/deepEMhancerModels/production_checkpoints/deepEMhancer_tightTarget.hd5 ... Traceback (most recent call last):
>   File "/home/john_doe/.local/bin/deepemhancer", line 8, in <module>
>     sys.exit(commanLineFun())
>   File "/home/john_doe/.local/lib/python3.7/site-packages/deepEMhancer/exeDeepEMhancer.py", line 80, in commanLineFun
>     main( ** parseArgs() )
>   File "/home/john_doe/.local/lib/python3.7/site-packages/deepEMhancer/exeDeepEMhancer.py", line 70, in main
>     predictor= AutoProcessVol(checkpoint_fname, gpuIds= gpuIds, batch_size= batch_size)
>   File "/home/john_doe/.local/lib/python3.7/site-packages/deepEMhancer/applyProcessVol/processVol.py", line 31, in __init__
>     self.model = load_model(model_fname, nGpus=nGpus )
>   File "/home/john_doe/.local/lib/python3.7/site-packages/deepEMhancer/utils/loadModel.py", line 19, in load_model
>     model= load_model(checkpoint_fname, custom_objects=custom_objects )
>   File "/home/john_doe/.local/lib/python3.7/site-packages/keras/engine/saving.py", line 458, in load_wrapper
>     return load_function(*args, **kwargs)
>   File "/home/john_doe/.local/lib/python3.7/site-packages/keras/engine/saving.py", line 550, in load_model
>     model = _deserialize_model(h5dict, custom_objects, compile)
>   File "/home/john_doe/.local/lib/python3.7/site-packages/keras/engine/saving.py", line 242, in _deserialize_model
>     model_config = json.loads(model_config.decode('utf-8'))
> AttributeError: 'str' object has no attribute 'decode'

When running the test command after installing:
`python3 -c "from tensorflow.python.client import device_lib; print(device_lib.list_local_devices())"`

I get successful messages:

> 2022-05-26 21:43:01.228111: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2022-05-26 21:43:01.244659: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2299995000 Hz
> 2022-05-26 21:43:01.244910: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x14e13e0 executing computations on platform Host. Devices:
> 2022-05-26 21:43:01.244989: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
> 2022-05-26 21:43:01.247381: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
> 2022-05-26 21:43:01.955024: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2022-05-26 21:43:01.955577: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x131e2f0 executing computations on platform CUDA. Devices:
> 2022-05-26 21:43:01.955656: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Graphics Device, Compute Capability 7.5
> 2022-05-26 21:43:01.955907: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2022-05-26 21:43:01.956293: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
> name: Graphics Device major: 7 minor: 5 memoryClockRate(GHz): 1.59
> pciBusID: 0000:00:04.0
> 2022-05-26 21:43:01.956650: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
> 2022-05-26 21:43:01.958009: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
> 2022-05-26 21:43:01.959307: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
> 2022-05-26 21:43:01.959661: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
> 2022-05-26 21:43:01.961328: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
> 2022-05-26 21:43:01.962599: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
> 2022-05-26 21:43:01.966350: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
> 2022-05-26 21:43:01.966508: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2022-05-26 21:43:01.966916: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2022-05-26 21:43:01.967294: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
> 2022-05-26 21:43:01.967376: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
> 2022-05-26 21:43:01.968178: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2022-05-26 21:43:01.968238: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0
> 2022-05-26 21:43:01.968282: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
> 2022-05-26 21:43:01.968530: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2022-05-26 21:43:01.968926: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2022-05-26 21:43:01.969283: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/device:GPU:0 with 14202 MB memory) -> physical GPU (device: 0, name: Graphics Device, pci bus id: 0000:00:04.0, compute capability: 7.5)
> [name: "/device:CPU:0"
> device_type: "CPU"
> memory_limit: 268435456
> locality {
> }
> incarnation: 11334920851672866655
> , name: "/device:XLA_CPU:0"
> device_type: "XLA_CPU"
> memory_limit: 17179869184
> locality {
> }
> incarnation: 10112785603461530163
> physical_device_desc: "device: XLA_CPU device"
> , name: "/device:XLA_GPU:0"
> device_type: "XLA_GPU"
> memory_limit: 17179869184
> locality {
> }
> incarnation: 11427042601074588166
> physical_device_desc: "device: XLA_GPU device"
> , name: "/device:GPU:0"
> device_type: "GPU"
> memory_limit: 14892338381
> locality {
>   bus_id: 1
>   links {
>   }
> }
> incarnation: 11148704270386205271
> physical_device_desc: "device: 0, name: Graphics Device, pci bus id: 0000:00:04.0, compute capability: 7.5"
> ]
> 

Any help with this would be awesome! I am installing this tool on a VM for one of our scientists to use.

**Comment by rsanchezgarc** [comment]
Hi,


It sounds like this:
https://stackoverflow.com/questions/53740577/does-any-one-got-attributeerror-str-object-has-no-attribute-decode-whi

Could you please report which are the conda environment packages you installed?
```
conda activate deepEMhancer_env
conda env export 
```

**Comment by JYlag** [comment]
Thanks for your quick response. The solution in that link worked for me!

So I actually am not using conda for my installation but just downgraded the h5py to version 2.10.0 and am no longer getting the error.
