### ISSUE TITLE
Clarity on official release!

### ISSUE THREAD

**Issue by sakoht** [rsanchezgarc/deepEMhancer#23]
I notice you have one tag, for version 0.14, made in December.  The instructions indicate to go from the `main` branch of the repo when installing.

Is the December release the "stable" version of the code, or are most users just using whatever is in `main` at the time?

Thanks in advance!

**Comment by rsanchezgarc** [comment]
Hi,

The tag 0.1 is an archived version that used Tensorflow v1.*. Thus, it won't work in newer GPUs. The master branch is the recommended for most users

**Comment by sakoht** [comment]
Thanks!
