### ISSUE TITLE
keep_dims vs keepdims

### ISSUE THREAD

**Issue by james-vincent** [rsanchezgarc/deepEMhancer#26]
Installing from latest source gives error with argument keep_dims:
`    deepemhancer/0.16/lib/python3.9/site-packages/keras_contrib/backend/tensorflow_backend.py", line 156, in moments  *
        return tf.nn.moments(x, axes, shift=shift, keep_dims=keep_dims)

    TypeError: Got an unexpected keyword argument 'keep_dims`

Apparently keep_dims arg changed to keepdims from tensorflow 1 to tensorflow 2. Not sure how this source code can work with keep_dims still there.

**Comment by rsanchezgarc** [comment]
Hi,

I am pretty sure that you are using the deepEMhancer models for tensorflow1 with tensorflow2 code. May I ask you to re-download the models?

You should see this url "https://zenodo.org/record/7432763/files/deepEMhancerModels_tf2.zip"
The same applies to #27
