### ISSUE TITLE
keras-contrib and keras_radam not install as part of deps in yml file

### ISSUE THREAD

**Issue by james-vincent** [rsanchezgarc/deepEMhancer#27]
keras-contrib and keras_radam  are installed in prior versions but are missing in .yml file in current source code. 

deepemhancer/0.16/lib/python3.9/site-packages/deepEMhancer/utils/loadModel.py", line 96, in retrieveParamsFromHd5
    exec(codeStr, env)  # normFun is in the code
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'keras_radam'

**Comment by rsanchezgarc** [comment]
Same as in #26. Those dependencies are no longer used

**Comment by james-vincent** [comment]
Thanks for the quick response. The new models have resolved these issues.


James Vincent, PhD
Bioinformatics Software Curator
Dept. of BCMP, Harvard Medical School
— BioGrids.org --
