### ISSUE TITLE
Reason(s) for oauth dependencies

### ISSUE THREAD

**Issue by yghorbal** [rsanchezgarc/deepEMhancer#31]
Hello,

 Just wondering what is the main reason(s) behind oauth dependencies expressed in deepEMhancer_env.yml. For instance:
 - google-auth==2.21.0
 - google-auth-oauthlib==1.0.0
 - oauthlib==3.2.2
 - requests-oauthlib==1.3.1
 
 Thank you for your assistance.

**Comment by rsanchezgarc** [comment]
Hi,
I am not sure; they might be dependencies installed by Tensorflow. deepEMhancer_env.yml is the output of conda env export, so it contains all the installed packages. But if you can install Tensorflow without them, then you won't need them.

You are welcome!

**Comment by yghorbal** [comment]
Indeed, it was a dep for Tensorflow!
