### ISSUE TITLE
Readme file Å character causes install errors on some python versions

### ISSUE THREAD

**Issue by GlazerMann** [rsanchezgarc/deepEMhancer#5]
ERROR: Command errored out with exit status 1:
     command: python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-7trizlpc/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-7trizlpc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-r_fcy0gp
         cwd: /tmp/pip-req-build-7trizlpc/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-7trizlpc/setup.py", line 22, in <module>
        long_description=readme(),
      File "/tmp/pip-req-build-7trizlpc/setup.py", line 11, in readme
        return f.read()
      File "/home/scicons/cascade/apps/DeepEMhancer/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6489: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by rsanchezgarc** [comment]
Thank you very much for reporting this.

It should be working now.

**Comment by GlazerMann** [comment]
Thank you.
